In [40]:
#Usando NumPy, importe o [dataset iris](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) mantendo 
#o seu conteúdo intacto.
import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='object', encoding='ascii')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [5]:
#Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.

import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='object', encoding='ascii')
iris[:,4]


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [4]:

#Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='float', usecols=[0])

media = np.mean(iris)
mediana = np.median(iris)
desvio = np.std(iris)

print('Média = ' + str(media))
print('Mediana = ' + str(mediana))
print('Desvio Padrão = ' + str(desvio))

Média = 5.843333333333334
Mediana = 5.8
Desvio Padrão = 0.8253012917851409


In [7]:

#Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='float', usecols=[0])

minimo = min(iris)
maximo = max(iris)

for i in range(len(iris)):
    iris[i] = (iris[i] - minimo) / (maximo - minimo)

print(iris)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [8]:

#Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='float', usecols=[0])

print(np.percentile(iris, 95))
print(np.percentile(iris, 5))


7.254999999999998
4.6


In [9]:

#Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

lista_pos = []
quant = 0

x = np.isnan(iris_2d[:,0])

for i in range(len(x)):
    if x[i] == True:
        quant += 1
        lista_pos.append(i)
print('Existem ' + str(quant) + ' valores ausentes')
print('Posições de valores ausentes')
print(lista_pos)


Existem 3 valores ausentes
Posições de valores ausentes
[77, 108, 125]


In [10]:
#Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

terceira = iris_2d[:,2]
primeira = iris_2d[:,0]

for i in range(len(iris_2d)):
    if terceira[i] <= 1.5:
        terceira[i] = 0
    if primeira[i] >= 5:
        primeira[i] = 0

print('Terceira')
for i in range(len(iris_2d)):
    if terceira[i] != 0 and np.isnan(terceira[i]) == False:
        print(str(terceira[i]) + ', ')

print('Primeira')
for i in range(len(iris_2d)):
    if primeira[i] != 0 and np.isnan(primeira[i]) == False:
        print(str(primeira[i]) + ', ')


Terceira
1.7, 
1.6, 
1.7, 
1.7, 
1.7, 
1.9, 
1.6, 
1.6, 
1.6, 
1.6, 
1.9, 
1.6, 
4.7, 
4.5, 
4.9, 
4.0, 
4.6, 
4.5, 
4.7, 
3.3, 
4.6, 
3.9, 
3.5, 
4.2, 
4.0, 
4.7, 
3.6, 
4.4, 
4.5, 
4.1, 
4.5, 
3.9, 
4.8, 
4.0, 
4.9, 
4.7, 
4.3, 
4.4, 
5.0, 
4.5, 
3.5, 
3.8, 
3.7, 
3.9, 
5.1, 
4.5, 
4.7, 
4.4, 
4.1, 
4.4, 
4.6, 
4.0, 
3.3, 
4.2, 
4.2, 
4.2, 
4.3, 
3.0, 
4.1, 
6.0, 
5.1, 
5.9, 
5.6, 
5.8, 
6.6, 
4.5, 
6.3, 
5.8, 
6.1, 
5.1, 
5.3, 
5.5, 
5.0, 
5.1, 
5.3, 
5.5, 
6.7, 
6.9, 
5.0, 
5.7, 
4.9, 
6.7, 
4.9, 
5.7, 
6.0, 
4.8, 
4.9, 
5.8, 
6.1, 
6.4, 
5.6, 
5.1, 
5.6, 
6.1, 
5.6, 
5.5, 
4.8, 
5.4, 
5.6, 
5.1, 
5.1, 
5.9, 
5.7, 
5.2, 
5.0, 
5.2, 
5.4, 
5.1, 
Primeira
4.9, 
4.7, 
4.6, 
4.6, 
4.4, 
4.9, 
4.8, 
4.8, 
4.3, 
4.6, 
4.8, 
4.7, 
4.8, 
4.9, 
4.9, 
4.4, 
4.5, 
4.4, 
4.8, 
4.9, 
4.9, 


In [11]:

# 15 . Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

for i in range(len(iris_2d)):
    if np.isnan(iris_2d[i]).all() == False:
        print(iris_2d[i])


[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.1 1.5 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

In [12]:
# Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

import numpy as np

data_url  = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(data_url, delimiter=',', dtype='float', usecols=[0,2])

cor = np.corrcoef(iris[:,0], iris[:,1])

print(cor)


[[1.         0.87175416]
 [0.87175416 1.        ]]


In [13]:
#Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

x = np.isnan(iris_2d)

if np.isin(False, iris_2d):
    print('Verdadeiro')
else:
    print('Falso')



Falso


In [14]:
#Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

for i in range(len(iris_2d)):
    for j in range(4):
        if np.isnan(iris_2d[i,j]).any() == True:
            iris_2d[i,j] = 0

print(iris_2d)



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 0.  1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 0.  1.6 0.2]
 [4.8 3.  1.4 0.1]
 [0.  3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0. ]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 0.  0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  0.  0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [15]:
#Encontre e conte os valores únicos da coluna species

import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='str', usecols=[4])

array_nome = []

for i in range(len(iris)):
    if array_nome.count(iris[i]) == 0:
        array_nome.append(iris[i])

print(array_nome)


['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']


In [17]:

#Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, 
#seguindo de acordo com a tabela abaixo:

#| Número               | Classificação                
#|:---------------------|:--------------|
#| Menor do que 3       | Pequena       |
#| entre 3 e 5          | Média         |
#| Maior ou Igual a 5   | Grande        |

import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[2])

iris_nova = []

for i in range(len(iris)):
    if iris[i] < 3:
        iris_nova.append('Pequena')
    elif iris[i] >= 3 and iris[i] < 5:
        iris_nova.append('Média')
    else:
        iris_nova.append('Grande')

print(iris_nova)
        


['Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Pequena', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Grande', 'Média', 'Média', 'Média', 'Média', 'Média', 'Grande', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média', 'Média

In [ ]:

#Crie uma nova coluna chamada *volume*, preenchida com dados resultantes da seguinte equação:
#$$volume=\frac{(~ Pi ~x~ Petallength ~x~ Sepal Length^2 ~)}{3}$$

In [25]:
#Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) 
#da espécie setosa?

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[2])

array = np.sort(iris)

print(array[len(array)-1])

6.9


In [30]:
#Ordene o dataset iris com base na coluna sepallength de maneira crescente.

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

array = np.sort(iris)

print(array)


[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]


In [33]:
#Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[2])

freq = 0
freq_posic = 0
list_iris = list(iris)

for i in range(len(iris)):
    if list_iris.count(list_iris[i]) > freq:
        freq = list_iris.count(iris[i])
        freq_posic = i
print(str(list_iris[freq_posic]) + ' é apresentado ' + str(freq) + ' vezes.')


1.5 é apresentado 14 vezes.


In [39]:
#Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.
